services:
  website1:
    build: .
    ports:
      - "4001:3000"
    volumes:
      - "/home/linuxserver/swoggerslol/client-swoggerslol/public:/app/client-swoggerslol/public"
      - "/home/linuxserver/swoggerslol/client-deadlab/public:/app/client-deadlab/public"
    env_file: .env

  website2:
    build: .
    ports:
      - "4002:3000"
    volumes:
      - "/home/linuxserver/swoggerslol/client-swoggerslol/public:/app/client-swoggerslol/public"
      - "/home/linuxserver/swoggerslol/client-deadlab/public:/app/client-deadlab/public"
    env_file: .env

  website3:
    build: .
    ports:
      - "4003:3000"
    volumes:
      - "/home/linuxserver/swoggerslol/client-swoggerslol/public:/app/client-swoggerslol/public"
      - "/home/linuxserver/swoggerslol/client-deadlab/public:/app/client-deadlab/public"
    env_file: .env